name: Continuous Integration

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o bin/musicCardMaker main.go

      - name: Test
        run: "go test ./..."

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57

      - name: Create git tag
        run: |
          git tag v${{ env.GitVersion_SemVer }}
          git push origin v${{ env.GitVersion_SemVer }}
